"""empty message

Revision ID: b2b4cec3d25a
Revises: 563ced4cffe3
Create Date: 2019-07-31 13:12:56.186918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b4cec3d25a'
down_revision = '563ced4cffe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_image')
    # ### end Alembic commands ###
